added licenses and repos for Beacon Network
GenomicDataInfrastructure/gdi-license-report pull request #3
Opened 2024-01-31 11:04 UTC by costero-e

Adding the repositories for the Beacon Network product (backend and UI).
Can you please review and accept @brunopacheco1 ?
Thank you,
Oriol

2024-01-31 15:13 UTC, brunopacheco1 commented
@costero-e thanks a lot for your PR.

Can you please also add these two repo in `.github/workflows/report_per_repo.yml`?

Then you will be able to get ORT repo for each of them.

2024-02-01 16:15 UTC, costero-e commented
hi @brunopacheco1,

I have added them now.

Tell me if now it's good to do the merge, please.

Thank you,

Oriol

2024-02-01 19:11 UTC, brunopacheco1 requested changes

2024-02-01 19:11 UTC, brunopacheco1 commented on .github/workflows/report_per_repo.yml
> -          - repository: NBISweden/sda-cli
You accidentally removed the repo `NBISweden/sda-cli`. Can you please add it back?

2024-02-02 08:12 UTC, costero-e commented
Hi @brunopacheco1, I'm sorry, I added it back now.

I hope everything is ready now to be merged.

Best,

Oriol

2024-02-02 12:59 UTC, brunopacheco1 approved these changes

2024-02-02 12:59 UTC, merged